import {
  aiRoboticsTraining,
  idmSapBOnePdf,
  idmSapPdf,
  idmSapHash,
  idmSap2,
  idmSap4,
  idmSap5,
  idmSap6,
  idmSchool1,
  // idmSchool2Heic,
  image1,
  image2,
  image3,
  image4,
  image5,
  image6,
  image7,
  image8,
  midgalSimba,
  polyProduct,
  sapPic1jpeg,
  schoolVideoMp4,
  school1Img,
  school2Img,
  school3,
  school4,
  school5,
  school6,
  school7,
  school8,
  school9,
  school10,
  school11,
  school12,
  school13,
  school14,
  school15,
  slotImg,
  triumph,
  veepee,
  videoMp4,
} from "./images";

export type MediaType = "image" | "video" | "pdf";

export interface MediaItem {
  title: string;
  caption: string;
  src: string;
  alt: string;
  type: MediaType;
  tab: string;
  downloadName?: string;
}

export const tabs = [
  { key: "school", label: "School" },
  { key: "idms", label: "IDMS" },
  { key: "outing", label: "Outing" },
  { key: "schoolRobotics", label: "School Robotics" },
  { key: "brochure", label: "Resources " },
];

export const mediaItems: MediaItem[] = [
  // school tabs
  {
    title: "School Event 1",
    caption: "Students presenting projects",
    src: school1Img,
    alt: "school 1",
    type: "image",
    tab: "school",
  },
  {
    title: "School Event 2",
    caption: "Workshop activity",
    src: school2Img,
    alt: "school 2",
    type: "image",
    tab: "school",
  },
  {
    title: "School Video",
    caption: "Highlights from the school program",
    src: schoolVideoMp4,
    alt: "school video",
    type: "video",
    tab: "school",
  },
  {
    title: "School 3",
    caption: "Classroom activities",
    src: school3,
    alt: "school 3",
    type: "image",
    tab: "school",
  },
  {
    title: "School 4",
    caption: "Student presentations",
    src: school4,
    alt: "school 4",
    type: "image",
    tab: "school",
  },
  {
    title: "School 5",
    caption: "Exhibition",
    src: school5,
    alt: "school 5",
    type: "image",
    tab: "school",
  },
  {
    title: "School 6",
    caption: "Awards and recognition",
    src: school6,
    alt: "school 6",
    type: "image",
    tab: "school",
  },
  {
    title: "School 7",
    caption: "Group photo",
    src: school7,
    alt: "school 7",
    type: "image",
    tab: "school",
  },
  {
    title: "School 8",
    caption: "Students on stage",
    src: school8,
    alt: "school 8",
    type: "image",
    tab: "school",
  },
  {
    title: "School 9",
    caption: "Winner team",
    src: school9,
    alt: "school 9",
    type: "image",
    tab: "school",
  },
  {
    title: "School 10",
    caption: "Classroom showcase",
    src: school10,
    alt: "school 10",
    type: "image",
    tab: "school",
  },
  {
    title: "School 11",
    caption: "Students presenting",
    src: school11,
    alt: "school 11",
    type: "image",
    tab: "school",
  },
  {
    title: "School 12",
    caption: "Workshop highlights",
    src: school12,
    alt: "school 12",
    type: "image",
    tab: "school",
  },
  {
    title: "School 13",
    caption: "Students & mentors",
    src: school13,
    alt: "school 13",
    type: "image",
    tab: "school",
  },
  {
    title: "School 14",
    caption: "Prize distribution",
    src: school14,
    alt: "school 14",
    type: "image",
    tab: "school",
  },
  {
    title: "School 15",
    caption: "Event group photo",
    src: school15,
    alt: "school 15",
    type: "image",
    tab: "school",
  },
  //    idmSapHash,
  //   idmSap2,
  //   idmSap4,
  //   idmSap5,
  //   idmSap6,
  //   idmSchool1,

  //   idms tab
  {
    title: "IDM Booth 1",
    caption: "",
    src: idmSapHash,
    alt: "idmSapHash ",
    type: "image",
    tab: "idms",
  },
  {
    title: "IDM Booth 2",
    caption: "",
    src: idmSap2,
    alt: "idmSap2 ",
    type: "image",
    tab: "idms",
  },
  {
    title: "IDM Booth 3",
    caption: "",
    src: idmSap4,
    alt: "idmSap4 ",
    type: "image",
    tab: "idms",
  },
  {
    title: "IDM Booth 4",
    caption: "",
    src: idmSap5,
    alt: "idmSap5 ",
    type: "image",
    tab: "idms",
  },
  {
    title: "IDM Booth 5",
    caption: "",
    src: idmSap6,
    alt: "idmSap6 ",
    type: "image",
    tab: "idms",
  },

  {
    title: "SPA 1 ",
    caption: "Event snapshot",
    src: image4,
    alt: "outing 1",
    type: "image",
    tab: "idms",
  },
  {
    title: "IDM Brochure Highlight",
    caption: "Marketing collateral",
    src: image1,
    alt: "idm 1",
    type: "image",
    tab: "outing",
  },
  {
    title: "IDM Booth",
    caption: "Expo booth",
    src: image2,
    alt: "idm 2",
    type: "image",
    tab: "outing",
  },
  {
    title: "IDM Team",
    caption: "Team at expo",
    src: image3,
    alt: "idm 3",
    type: "image",
    tab: "outing",
  },
  {
    title: "Outing 2",
    caption: "Community event",
    src: image5,
    alt: "outing 2",
    type: "image",
    tab: "outing",
  },
  {
    title: "Outing Video",
    caption: "Event film",
    src: videoMp4,
    alt: "outing video",
    type: "video",
    tab: "outing",
  },

  {
    title: "outing meeting",
    caption: "Demo session",
    src: image6,
    alt: "robotics demo",
    type: "image",
    tab: "outing",
  },
  {
    title: "Robotics Video",
    caption: "Robot in action",
    src: videoMp4,
    alt: "robotics video",
    type: "video",
    tab: "outing",
  },

  //

  {
    title: "Robotics Training",
    caption: "Robotics lab",
    src: aiRoboticsTraining,
    alt: "robotics",
    type: "image",
    tab: "schoolRobotics",
  },
  {
    title: "",
    caption: "",
    src: idmSchool1,
    alt: "idmSchool1 ",
    type: "image",
    tab: "schoolRobotics",
  },

  {
    title: "IDM & SAP B-One",
    caption: "Product brochure",
    src: idmSapBOnePdf,
    alt: "idm sap brochure",
    type: "pdf",
    tab: "brochure",
    downloadName: "IDM-SAP-B-One.pdf",
  },
  {
    title: "IDM Overview",
    caption: "Company brochure",
    src: idmSapPdf,
    alt: "idm pdf",
    type: "pdf",
    tab: "brochure",
    downloadName: "IDM-Overview.pdf",
  },
];
